exports.install = function (Vue, options) {
	Vue.prototype.game = {
		SportGame:[
			{
				gameCode: "code1", 
				gameTitle:"name1",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code2", 
				gameTitle:"name2",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code3", 
				gameTitle:"name3",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
		RealPeopleGame:[
			{
				gameCode: "code4", 
				gameTitle:"name4",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code5", 
				gameTitle:"name5",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code6", 
				gameTitle:"name6",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code7", 
				gameTitle:"name7",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
		ChessGame:[
			{
				gameCode: "code8", 
				gameTitle:"name8",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code9", 
				gameTitle:"name9",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code10", 
				gameTitle:"name10",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
		LotteryGame:[
			{
				gameCode: "code11", 
				gameTitle:"name11",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code12", 
				gameTitle:"name12",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code13", 
				gameTitle:"name13",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
		VideoGame:[
			{
				gameCode: "code14", 
				gameTitle:"name14",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code15", 
				gameTitle:"name15",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code16", 
				gameTitle:"name16",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code17", 
				gameTitle:"name17",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code18", 
				gameTitle:"name18",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code19", 
				gameTitle:"name19",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
		EsportsGame:[
			{
				gameCode: "code20", 
				gameTitle:"name20",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
			{
				gameCode: "code21", 
				gameTitle:"name21",
				homeGameImg:"",
				homeGameWhImg:"",
				gameMoney: "Loading..",
				p_status: 1,
			},
		],
	}
};
